import React from 'react';
import {
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Plus,
  BarChart,
  Building2,
  Building,
  Sparkles,
  Box,
  Cake,
  CalendarDays,
  MessageSquare,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronRight,
  X,
  CloudUpload,
  Trash2,
  FileText,
  Download,
  Edit3,
  AlertTriangle,
  ClipboardCheck,
  Folder,
  FolderOpen,
  Users,
  UserPlus,
  Info,
  Link,
  MapPin,
  Lock,
  Mail,
  MoreVertical,
  ExternalLink,
  Home,
  CreditCard,
  Banknote,
  Wallet,
  PlusCircle,
  Briefcase,
  LayoutDashboard,
  PenTool,
  Award,
  Bell,
  DollarSign,
  UserCog,
  Activity,
  Mountain,
  TrendingUp,
  Image,
  Film,
  Clock,
  Hourglass,
  User,
  Brain,
  RefreshCw,
  XCircle,
  CornerUpLeft,
  Search,
  Send,
  Settings,
  ThumbsUp,
  Upload,
  UploadCloud,
  Eye,
  Droplet,
} from 'lucide-react';

const iconMap = {
  add: Plus,
  analytics: BarChart,
  architecture: Building2,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  auto_awesome: Sparkles,
  box: Box,
  cake: Cake,
  calendar_month: CalendarDays,
  calendar_today: CalendarDays,
  chat: MessageSquare,
  check: Check,
  check_circle: CheckCircle,
  checklist: CheckSquare,
  chevron_right: ChevronRight,
  close: X,
  cloud_upload: CloudUpload,
  delete: Trash2,
  description: FileText,
  download: Download,
  edit: Edit3,
  error: AlertTriangle,
  fact_check: ClipboardCheck,
  folder: Folder,
  folder_open: FolderOpen,
  group: Users,
  group_add: UserPlus,
  info: Info,
  link: Link,
  location_on: MapPin,
  lock: Lock,
  mail: Mail,
  more_vert: MoreVertical,
  open_in_new: ExternalLink,
  payments: CreditCard,
  account_balance: Banknote,
  account_balance_wallet: Wallet,
  add_circle: PlusCircle,
  apartment: Building,
  attach_money: DollarSign,
  business: Briefcase,
  dashboard: LayoutDashboard,
  dashboard_customize: LayoutDashboard,
  domain: Home,
  draw: PenTool,
  emoji_events: Award,
  mail_outline: Mail,
  manage_accounts: UserCog,
  monetization_on: DollarSign,
  monitoring: Activity,
  movie: Film,
  notifications: Bell,
  panorama: Image,
  pending: Clock,
  pending_actions: Hourglass,
  task_alt: CheckCircle,
  terrain: Mountain,
  trending_up: TrendingUp,
  view_in_ar: Box,
  person: User,
  person_pin: User,
  psychology: Brain,
  receipt_long: FileText,
  refresh: RefreshCw,
  remove_circle: XCircle,
  reply: CornerUpLeft,
  schedule: Clock,
  search: Search,
  send: Send,
  settings: Settings,
  thumb_up: ThumbsUp,
  timeline: Clock,
  upload: Upload,
  upload_file: UploadCloud,
  visibility: Eye,
  warning: AlertTriangle,
  water_drop: Droplet,
};

const normalizeName = (name) => {
  if (typeof name !== 'string') return name;
  return name.replace(/\s+/g, '_').toLowerCase();
};

const Icon = ({ name, className = '', style, ...props }) => {
  const normalized = normalizeName(name);
  const Component = iconMap[normalized] || X;
  return <Component className={className} style={style} {...props} />;
};

export default Icon;
